"use client";

import { useRef, useState } from "react";
import { Camera, CheckCircle2, Download, FileCheck2, Fingerprint, MapPin, RefreshCw, ScanLine, ShieldCheck, UserPlus, X } from "lucide-react";

type Policy = { id: string; trader: string; market: string; cover: string; value: string; status: "Active" | "Review"; renewed: string };
type Claim = { id: string; trader: string; market: string; type: string; amount: string; status: "Open" | "Approved" | "Needs evidence"; filed: string };
type Trader = { id: string; name: string; stall: string; market: string; phone: string; stock: string; policies: number; status: "Protected" | "Action needed" };

const policies: Policy[] = [
  ["TC-1048", "Tendai Moyo", "Mbare Musika", "Stock cover", "US$ 680", "Active", "24 Sep 2026"], ["TC-1047", "Farai Ncube", "Siyaso Market", "Stock cover", "US$ 1,240", "Active", "24 Sep 2026"], ["TC-1046", "Rudo Chirwa", "Mbare Musika", "Stock + fire", "US$ 920", "Active", "23 Sep 2026"], ["TC-1045", "Munashe Dube", "Glen View 8", "Stock cover", "US$ 410", "Active", "23 Sep 2026"], ["TC-1044", "Chipo Zulu", "Siyaso Market", "Stock + theft", "US$ 2,100", "Review", "22 Sep 2026"], ["TC-1043", "Tafadzwa Mlambo", "Mbare Musika", "Stock cover", "US$ 760", "Active", "22 Sep 2026"], ["TC-1042", "Nyasha Sibanda", "Mupedzanhamo", "Stock cover", "US$ 535", "Active", "21 Sep 2026"], ["TC-1041", "Blessing Zhou", "Glen View 8", "Stock + fire", "US$ 1,480", "Active", "21 Sep 2026"], ["TC-1040", "Kundai Chikore", "Siyaso Market", "Stock cover", "US$ 350", "Active", "20 Sep 2026"], ["TC-1039", "Mavis Ndlovu", "Mbare Musika", "Stock + theft", "US$ 890", "Active", "20 Sep 2026"], ["TC-1038", "Tariro Gutu", "Mupedzanhamo", "Stock cover", "US$ 625", "Active", "19 Sep 2026"], ["TC-1037", "Admire Mapfumo", "Siyaso Market", "Stock cover", "US$ 1,020", "Active", "19 Sep 2026"], ["TC-1036", "Shingai Mupfumi", "Glen View 8", "Stock + fire", "US$ 740", "Review", "18 Sep 2026"], ["TC-1035", "Eunice Chuma", "Mbare Musika", "Stock cover", "US$ 460", "Active", "18 Sep 2026"], ["TC-1034", "Tinashe Hove", "Siyaso Market", "Stock + theft", "US$ 1,760", "Active", "17 Sep 2026"],
].map(([id, trader, market, cover, value, status, renewed]) => ({ id, trader, market, cover, value, status: status as Policy["status"], renewed }));

const claims: Claim[] = [
  ["CL-0291", "Tendai Moyo", "Mbare Musika", "Water damage", "US$ 420", "Open", "Today"], ["CL-0290", "Chipo Zulu", "Siyaso Market", "Stock theft", "US$ 680", "Needs evidence", "Yesterday"], ["CL-0289", "Farai Ncube", "Siyaso Market", "Fire damage", "US$ 1,140", "Open", "23 Sep"], ["CL-0288", "Rudo Chirwa", "Mbare Musika", "Water damage", "US$ 240", "Approved", "22 Sep"], ["CL-0287", "Munashe Dube", "Glen View 8", "Stock theft", "US$ 310", "Open", "21 Sep"], ["CL-0286", "Nyasha Sibanda", "Mupedzanhamo", "Transit damage", "US$ 190", "Approved", "20 Sep"], ["CL-0285", "Blessing Zhou", "Glen View 8", "Fire damage", "US$ 740", "Needs evidence", "20 Sep"], ["CL-0284", "Kundai Chikore", "Siyaso Market", "Stock theft", "US$ 280", "Open", "19 Sep"], ["CL-0283", "Mavis Ndlovu", "Mbare Musika", "Water damage", "US$ 365", "Approved", "18 Sep"], ["CL-0282", "Tariro Gutu", "Mupedzanhamo", "Stock theft", "US$ 515", "Open", "17 Sep"], ["CL-0281", "Admire Mapfumo", "Siyaso Market", "Fire damage", "US$ 920", "Needs evidence", "16 Sep"], ["CL-0280", "Shingai Mupfumi", "Glen View 8", "Water damage", "US$ 275", "Approved", "15 Sep"], ["CL-0279", "Eunice Chuma", "Mbare Musika", "Transit damage", "US$ 155", "Open", "14 Sep"], ["CL-0278", "Tinashe Hove", "Siyaso Market", "Stock theft", "US$ 490", "Approved", "13 Sep"], ["CL-0277", "Tafadzwa Mlambo", "Mbare Musika", "Water damage", "US$ 330", "Open", "12 Sep"],
].map(([id, trader, market, type, amount, status, filed]) => ({ id, trader, market, type, amount, status: status as Claim["status"], filed }));

const traders: Trader[] = [
  ["TR-184", "Tendai Moyo", "Stall B14", "Mbare Musika", "+263 77 245 0198", "US$ 680", 2, "Protected"], ["TR-183", "Farai Ncube", "Stall C06", "Siyaso Market", "+263 71 420 8871", "US$ 1,240", 3, "Protected"], ["TR-182", "Rudo Chirwa", "Stall A09", "Mbare Musika", "+263 78 330 1142", "US$ 920", 1, "Protected"], ["TR-181", "Munashe Dube", "Stall D02", "Glen View 8", "+263 77 819 3021", "US$ 410", 1, "Action needed"], ["TR-180", "Chipo Zulu", "Stall C19", "Siyaso Market", "+263 71 650 7783", "US$ 2,100", 4, "Protected"], ["TR-179", "Tafadzwa Mlambo", "Stall B03", "Mbare Musika", "+263 78 114 6002", "US$ 760", 2, "Protected"], ["TR-178", "Nyasha Sibanda", "Stall M11", "Mupedzanhamo", "+263 77 504 9210", "US$ 535", 1, "Protected"], ["TR-177", "Blessing Zhou", "Stall D17", "Glen View 8", "+263 71 991 4430", "US$ 1,480", 2, "Action needed"], ["TR-176", "Kundai Chikore", "Stall C03", "Siyaso Market", "+263 78 240 3159", "US$ 350", 1, "Protected"], ["TR-175", "Mavis Ndlovu", "Stall B21", "Mbare Musika", "+263 77 622 8470", "US$ 890", 2, "Protected"], ["TR-174", "Tariro Gutu", "Stall M04", "Mupedzanhamo", "+263 71 328 5120", "US$ 625", 1, "Protected"], ["TR-173", "Admire Mapfumo", "Stall C12", "Siyaso Market", "+263 78 440 2183", "US$ 1,020", 2, "Protected"], ["TR-172", "Shingai Mupfumi", "Stall D08", "Glen View 8", "+263 77 201 9044", "US$ 740", 1, "Action needed"], ["TR-171", "Eunice Chuma", "Stall B08", "Mbare Musika", "+263 71 872 6601", "US$ 460", 1, "Protected"], ["TR-170", "Tinashe Hove", "Stall C25", "Siyaso Market", "+263 78 318 0906", "US$ 1,760", 3, "Protected"],
].map(([id, name, stall, market, phone, stock, policiesCount, status]) => ({ id: String(id), name: String(name), stall: String(stall), market: String(market), phone: String(phone), stock: String(stock), policies: Number(policiesCount), status: status as Trader["status"] }));

function ActionButton({ children, onClick, icon }: { children: React.ReactNode; onClick: () => void; icon?: React.ReactNode }) {
  return <button className="outline-action tool-button" type="button" onClick={onClick}>{icon}{children}</button>;
}

export function WorkspaceTools({ section }: { section: string }) {
  if (section === "policies") return <PolicyTool />;
  if (section === "claims") return <ClaimTool />;
  if (section === "traders") return <TraderTool />;
  if (section === "capture") return <CaptureTool />;
  return null;
}

function PolicyTool() {
  const [selected, setSelected] = useState<Policy | null>(null);
  const [status, setStatus] = useState("Select a policy to open its certificate and activity.");
  return <div className="data-tool"><div className="tool-heading"><div><p className="eyebrow">Live register</p><h2>15 recent policies</h2><p>Choose a policy to inspect cover, renewal date, and the trader’s market context.</p></div><ActionButton icon={<Download size={14} />} onClick={() => setStatus("Policy register prepared for download.")}>Export register</ActionButton></div><div className="tool-select-row"><label htmlFor="policy-select">Open a policy</label><select id="policy-select" defaultValue="" onChange={(event) => setSelected(policies.find((policy) => policy.id === event.target.value) ?? null)}><option value="">Select policy ID or trader</option>{policies.map((policy) => <option key={policy.id} value={policy.id}>{policy.id} · {policy.trader} · {policy.market}</option>)}</select></div><div className="data-table">{policies.map((policy) => <button className="data-row" type="button" key={policy.id} onClick={() => setSelected(policy)}><span><strong>{policy.id}</strong><small>{policy.trader} · {policy.market}</small></span><span><strong>{policy.value}</strong><small>{policy.cover} · renewed {policy.renewed}</small></span><span className={`status ${policy.status === "Active" ? "status-active" : "status-review"}`}>{policy.status}</span></button>)}</div><p className="tool-feedback" role="status">{status}</p>{selected && <DetailDialog title={`Policy ${selected.id}`} onClose={() => setSelected(null)}><div className="detail-grid"><span>Trader<strong>{selected.trader}</strong></span><span>Market<strong>{selected.market}</strong></span><span>Protection<strong>{selected.cover}</strong></span><span>Insured value<strong>{selected.value}</strong></span></div><ActionButton icon={<FileCheck2 size={14} />} onClick={() => setStatus(`Certificate for ${selected.id} opened.`)}>Open certificate</ActionButton></DetailDialog>}</div>;
}

function ClaimTool() {
  const [selected, setSelected] = useState<Claim | null>(null);
  const [claimState, setClaimState] = useState<Record<string, Claim["status"]>>({});
  const [status, setStatus] = useState("Open a claim to review evidence and payout context.");
  return <div className="data-tool"><div className="tool-heading"><div><p className="eyebrow">Claims queue</p><h2>15 recent claims</h2><p>Each claim is tied to a trader, market, incident type, and evidence requirement.</p></div><ActionButton icon={<Download size={14} />} onClick={() => setStatus("Claims queue prepared for download.")}>Export claims</ActionButton></div><div className="data-table">{claims.map((claim) => { const currentStatus = claimState[claim.id] ?? claim.status; return <button className="data-row" type="button" key={claim.id} onClick={() => setSelected(claim)}><span><strong>{claim.id}</strong><small>{claim.trader} · {claim.market}</small></span><span><strong>{claim.amount}</strong><small>{claim.type} · filed {claim.filed}</small></span><span className={`status ${currentStatus === "Approved" ? "status-active" : "status-review"}`}>{currentStatus}</span></button>; })}</div><p className="tool-feedback" role="status">{status}</p>{selected && <DetailDialog title={`Claim ${selected.id}`} onClose={() => setSelected(null)}><p className="detail-copy"><strong>{selected.type}</strong> reported by {selected.trader} at {selected.market}. The requested payout is {selected.amount}; evidence and stock history are attached to this review.</p><div className="detail-actions"><ActionButton onClick={() => { setClaimState((current) => ({ ...current, [selected.id]: "Approved" })); setStatus(`${selected.id} approved for payout.`); setSelected(null); }} icon={<CheckCircle2 size={14} />}>Approve payout</ActionButton><ActionButton onClick={() => { setClaimState((current) => ({ ...current, [selected.id]: "Needs evidence" })); setStatus(`Evidence requested from ${selected.trader}.`); setSelected(null); }} icon={<ScanLine size={14} />}>Request evidence</ActionButton></div></DetailDialog>}</div>;
}

function TraderTool() {
  const [selected, setSelected] = useState<Trader | null>(null);
  const [status, setStatus] = useState("Select a trader to view their cover history and stock context.");
  return <div className="data-tool"><div className="tool-heading"><div><p className="eyebrow">Market directory</p><h2>15 active traders</h2><p>Know where each trader works, what they carry, and whether their cover needs attention.</p></div><ActionButton icon={<UserPlus size={14} />} onClick={() => setStatus("Invite link created for a new trader.")}>Invite trader</ActionButton></div><div className="data-table">{traders.map((trader) => <button className="data-row" type="button" key={trader.id} onClick={() => setSelected(trader)}><span><strong>{trader.name}</strong><small>{trader.id} · {trader.stall} · {trader.market}</small></span><span><strong>{trader.stock}</strong><small>{trader.policies} active polic{trader.policies === 1 ? "y" : "ies"}</small></span><span className={`status ${trader.status === "Protected" ? "status-active" : "status-review"}`}>{trader.status}</span></button>)}</div><p className="tool-feedback" role="status">{status}</p>{selected && <DetailDialog title={selected.name} onClose={() => setSelected(null)}><div className="detail-grid"><span>Location<strong>{selected.stall}, {selected.market}</strong></span><span>Phone<strong>{selected.phone}</strong></span><span>Covered stock<strong>{selected.stock}</strong></span><span>Policies<strong>{selected.policies} active</strong></span></div><ActionButton icon={<ShieldCheck size={14} />} onClick={() => setStatus(`Cover history for ${selected.name} opened.`)}>View cover history</ActionButton></DetailDialog>}</div>;
}

function CaptureTool() {
  const videoRef = useRef<HTMLVideoElement>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const [cameraState, setCameraState] = useState<"idle" | "checking" | "ready" | "denied">("idle");
  const [message, setMessage] = useState("Use a live camera capture so the evidence has a verifiable origin.");

  async function startCamera() {
    setCameraState("checking");
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" }, audio: false });
      streamRef.current = stream;
      if (videoRef.current) videoRef.current.srcObject = stream;
      setCameraState("ready");
      setMessage("Live feed ready. Complete the server verification before this capture can support a claim.");
    } catch { setCameraState("denied"); setMessage("Camera access was not granted. No upload is accepted as verified evidence."); }
  }

  function stopCamera() { streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = null; setCameraState("idle"); setMessage("Camera stopped. Start again when the stock is in frame."); }

  return <div className="capture-tool"><div className="tool-heading"><div><p className="eyebrow">Evidence integrity</p><h2>Verify stock before cover</h2><p>Capture live evidence with device, time, and market signals attached. Verification is designed for a Google Cloud backend using Vision and Vertex AI checks.</p></div><span className="security-badge"><ShieldCheck size={14} /> Secure capture</span></div><div className="capture-grid"><div className="camera-stage">{cameraState === "ready" ? <video ref={videoRef} autoPlay playsInline muted /> : <div className="camera-placeholder"><Camera size={30} /><span>{cameraState === "checking" ? "Checking camera access..." : "Camera preview"}</span></div>}{cameraState === "ready" ? <ActionButton icon={<X size={14} />} onClick={stopCamera}>Stop camera</ActionButton> : <ActionButton icon={<Camera size={14} />} onClick={startCamera}>Start live capture</ActionButton>}</div><div className="verification-panel"><p className="eyebrow">Verification chain</p><VerificationRow icon={<Fingerprint size={16} />} title="Device attestation" detail="Bind capture to a registered device" /><VerificationRow icon={<MapPin size={16} />} title="Time + market location" detail="Compare against policy and stall record" /><VerificationRow icon={<ScanLine size={16} />} title="Google Vision / Vertex AI" detail="Server checks for manipulation, replay, and inconsistent stock" /><div className={`capture-message capture-message-${cameraState}`} role="status">{message}</div><ActionButton icon={<RefreshCw size={14} />} onClick={() => setMessage("Verification request queued. A trusted backend must issue the final evidence verdict.")}>Run verification</ActionButton></div></div><p className="capture-note">A browser alone cannot prove that a video is genuine or that stock is not counterfeit. The production API should require an attested live capture, signed metadata, replay detection, and human review before accepting a claim.</p></div>;
}

function VerificationRow({ icon, title, detail }: { icon: React.ReactNode; title: string; detail: string }) { return <div className="verification-row"><span className="verification-icon">{icon}</span><span><strong>{title}</strong><small>{detail}</small></span><CheckCircle2 size={15} /></div>; }
function DetailDialog({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="detail-overlay" role="dialog" aria-modal="true" aria-label={title}><div className="detail-dialog"><div className="detail-header"><h3>{title}</h3><button className="icon-button" type="button" aria-label="Close details" onClick={onClose}><X size={16} /></button></div>{children}</div></div>; }